pipeline {
    agent any

    tools {
        maven 'Maven-3.9.6'
    }

    
    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/aishu-java/java-devops-demo.git'
            }
        }

      stage('Check Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

      stage('Build') {
    steps {
        dir('java-devops-demo') {
            sh 'mvn clean package'
        }
    }
}
    }
}
